### ISSUE TITLE
Ho to optimize resize quality ? 

### ISSUE THREAD

**Issue by Aarbel** [csbun/resize-image#18]
I resize a very big image (12288 × 12288) to a small image (512x512) with this library.

I have big image quality issues while resizing, how to fix this quality problem ?
Thanks a lot for your help !

My code
```JS
const zoomRoot = bigSquareImageClone
        .resize({ 'width': 512, 'height': 512 });
```

Original (screenshot un-zoomed)
![image](https://user-images.githubusercontent.com/25119847/73957605-e2af6b80-4906-11ea-9fc0-e96a9f28b36e.png)

Resized: Screenshot 100%
![image](https://user-images.githubusercontent.com/25119847/73957623-ea6f1000-4906-11ea-9437-9aa14e290556.png)

**Comment by Aarbel** [comment]
@csbun

**Comment by csbun** [comment]
Never face this case before. I think it might because I draw the original image into resized canvas directly.

**Comment by Aarbel** [comment]
My best option to avoid this bad resizing behavior was to use sharp
